feat: numbering every word in a file
power-scripting/powershell-one-liners pull request #7
Opened 2020-05-05 11:08 UTC by sharma-shruti

2020-05-05 13:45 UTC, abhi18av requested changes
Also, maybe it's better to include the contents of the sample file like so

```
file contents 
.
.
.
```

Notes
```
perl stuff
```
Notes
```
powershell stuff
```

2020-05-05 13:45 UTC, abhi18av commented on src/numbering_words_in_a_file.md
> +*I spent 2 pomodoro on this task*
```suggestion
Pomodoros: 2
```

2020-05-05 14:01 UTC, closed without merging

2020-05-05 14:08 UTC, abhi18av commented
@sharma-shruti , Github automatically closed this PR since I've reworked the `develop` branch git history. Now you need to fix this situation and then reopen/re-initiate this PR.

Here are some hints
- `rebase`
- `cherry-pick`
- `patch`

2020-05-06 05:00 UTC, sharma-shruti commented
Pomodoro: 3
I think I did something wrong. The file was present in my feature branch so I cherry-picked it on develop branch. But I still don't see this file on origin/develop.
```
Ashwarys-MBP:powershell-one-liners ashwarybhatt$ git cherry-pick d4b8415d47385471c46075855fb4b41e4f6ccd44
[develop d2a05db] feat: numbering every word in a file
 Date: Tue May 5 19:07:20 2020 +0800
 1 file changed, 36 insertions(+)
 create mode 100644 src/numbering_words_in_a_file.md
Ashwarys-MBP:powershell-one-liners ashwarybhatt$ git log
commit d2a05dbef38aa9e05f774ffdc7671fdee79e8542 (HEAD -> develop)
Author: Shruti <shruti26.inbox@gmail.com>
Date:   Tue May 5 19:07:20 2020 +0800

    feat: numbering every word in a file

commit 662a8fae0ee72e6d78422c7b8978e5f263187fa4
Author: Shruti <shruti26.inbox@gmail.com>
Date:   Mon May 4 23:46:17 2020 +0800

    feat: remove blank lines from a file
=============================================
Ashwarys-MBP:powershell-one-liners ashwarybhatt$ git status
On branch develop
Your branch and 'origin/develop' have diverged,
and have 6 and 5 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean
Ashwarys-MBP:powershell-one-liners ashwarybhatt$
```
When I tried **git pull** it says `no merge base found.`

2020-05-06 08:01 UTC, abhi18av commented
@sharma-shruti , you shouldn't cherry-pick onto the `develop` or `master`. Think of both are immutable/unmodifiable branches.

Give this one more pomodoro, then simply 
- delete your local develop / master and pull both again to local
- start new feature branch from the updated develop
- cherry pick only your commits from this branch onto the new feature branch
- initiate another PR

2020-05-06 11:25 UTC, sharma-shruti commented
I followed the steps but still unable to push my changes to remote and create a pull request because of the following error.
```
ashwarys-mbp:powershell-one-liners ashwarybhatt$ git log
commit 6f949563d13850ecb4355a0ece46881a3e17ba2a (HEAD -> feature/number_words)
Author: Shruti <shruti26.inbox@gmail.com>
Date:   Tue May 5 19:07:20 2020 +0800

    feat: numbering every word in a file

commit 0fdf6b9f6eb53b1c8f6cc3a6bf6c9e9dc278878a (origin/master, origin/develop, origin/HEAD, develop)
Author: Shruti <shruti26.inbox@gmail.com>
Date:   Mon May 4 23:46:17 2020 +0800

    feat: remove blank lines from a file
```
![2020-05-06 19 20 42](https://user-images.githubusercontent.com/61221967/81171347-d0f56700-8fce-11ea-9333-580f92a23b7f.gif)

![2020-05-06 19 23 15](https://user-images.githubusercontent.com/61221967/81171527-19148980-8fcf-11ea-96aa-7ffa7a63c035.gif)

2020-05-06 11:30 UTC, abhi18av commented
@sharma-shruti , no worries. We'll connect tonight for this hmm 

Please continue with the other commands/features